spring.application.name=ms-productos-financieros

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.audiences=web-app

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/reto-tecnico
spring.r2dbc.username=myuser
spring.r2dbc.password=secret

spring.sql.init.mode=always

logging.level.org.springframework.security=TRACE
server.port=8083

spring.webflux.base-path= /api/v1

management.tracing.sampling.probability= 1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.include-application-name=false
management.tracing.enabled=false


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.use-root-path=false
springdoc.swagger-ui.url=/api/openapi.yaml